// Generated by CoffeeScript 1.10.0
(function() {
  modules.action = {
    add: {
      submit: function(event) {
        var input;
        event.preventDefault();
        input = $('.editor-field input').val().shorten();
        if (input) {
          modules.ajax.add(input);
          $('.editor-field input').val('');
          return $('ul').append("<li><input type='checkbox' /><span>" + input + "</span>  <button>Remove</button></li>");
        } else {
          return alert("Error! Invalid task!");
        }
      }
    },
    change: {
      submit: function(event) {
        var changedTask;
        event.preventDefault();
        changedTask = {
          newTask: $(this).serializeArray()[0].value.shorten(),
          id: $(this).parent().parent().data("id")
        };
        if (changedTask.newTask) {
          $(this).parent().html("" + changedTask.newTask);
          return modules.ajax.change(changedTask);
        } else {
          return alert('Error! Invalid task!');
        }
      },
      dblclick: function(event) {
        var html, value;
        event.preventDefault();
        value = $(this).html();
        html = "<form autocomplete=\"off\" id=\"changing\"><input name=\"task\" type=\"text\" value=\"" + value + "\" autofocus/></form>";
        $(this).html(html);
        $(this).children('input').first().focus();
        return $('#changing').on('submit', modules.action.change.submit);
      }
    },
    remove: {
      click: function() {
        var li;
        if (confirm('Are you sure?')) {
          li = $(this).parent();
          modules.ajax.remove(parseInt(li.data('id')));
          return li.remove();
        }
      }
    }
  };

}).call(this);
