// Generated by CoffeeScript 1.10.0
(function() {
  modules.ajax = {
    add: (function(_this) {
      return function(input) {
        return $.ajax('/Home/Add', {
          type: "POST",
          data: $('form').serialize(),
          beforeSend: function() {},
          success: function(response) {
            response = parseInt(response);
            if (response === -1) {
              return alert("Error!");
            } else {
              console.log('Should add attr');
              return $('ul').children('li').last().attr('data-id', response);
            }
          },
          timeout: 3000,
          error: _this.error,
          complete: function() {}
        });
      };
    })(this),
    change: (function(_this) {
      return function(changedTask) {
        return $.ajax('/Home/Change', {
          type: "POST",
          data: changedTask,
          beforeSend: function() {},
          success: function(response) {
            response = parseInt(response);
            console.log(response);
            if (response === -1) {
              return alert("Error!");
            }
          },
          timeout: 3000,
          error: _this.error,
          complete: function() {}
        });
      };
    })(this),
    remove: function(id) {
      return $.ajax('/Home/Remove', {
        type: "POST",
        data: {
          id: id
        },
        beforeSend: function() {},
        success: function(response) {
          console.log(response);
          response = parseInt(response);
          if (response === -1) {
            return alert('Error!');
          } else {
            console.log($(this));
            return $(this).remove();
          }
        },
        timeout: 3000,
        error: modules.ajax.error,
        complete: function() {
          return console.log("Loading finished! [clientside]");
        }
      });
    },
    error: function(request, errorType, errorMessage) {
      alert("Error! " + errorMessage + "!");
      return console.log("Error \"" + errorType + "\": " + errorMessage + "!");
    }
  };

}).call(this);
