// Generated by CoffeeScript 1.10.0
(function() {
  modules.ajax = {
    add: (function(_this) {
      return function(input) {
        return $.ajax('Home/Add', {
          type: "POST",
          data: $('form').serialize(),
          beforeSend: function() {},
          success: function(response) {
            response = parseInt(response);
            if (response === -1) {
              return alert("Error!");
            } else {
              return $('ul').children('li').last().attr('data-id', response);
            }
          },
          timeout: 3000,
          error: _this.error,
          complete: function() {}
        });
      };
    })(this),
    change: (function(_this) {
      return function(changedTask) {
        return $.ajax('Home/Change', {
          type: "POST",
          data: changedTask,
          beforeSend: function() {},
          success: function(response) {
            response = parseInt(response);
            if (response === -1) {
              return alert("Error!");
            }
          },
          timeout: 3000,
          error: _this.error,
          complete: function() {}
        });
      };
    })(this),
    sendId: function(id, url) {
      return $.ajax(url, {
        type: "POST",
        data: {
          id: id
        },
        beforeSend: function() {},
        success: function(response) {
          response = parseInt(response);
          if (response === -1) {
            return alert('Error!');
          } else {
            return $(this).remove();
          }
        },
        timeout: 3000,
        error: modules.ajax.error,
        complete: function() {
          return console.log("Loading finished! [clientside]");
        }
      });
    },
    remove: function(id) {
      return modules.ajax.sendId(id, 'Home/Remove');
    },
    changeStatus: function(id) {
      return modules.ajax.sendId(id, 'Home/Done');
    },
    error: function(request, errorType, errorMessage) {
      alert("Error! " + errorMessage + "!");
      return console.log("Error \"" + errorType + "\": " + errorMessage + "!");
    }
  };

}).call(this);
