// Generated by CoffeeScript 1.10.0
(function() {
  String.prototype.shorten = function() {
    var i, j, ref, shorten, words;
    words = this.split(' ');
    shorten = '';
    for (i = j = 0, ref = words.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      if (words[i]) {
        shorten += words[i] + ' ';
      }
    }
    if (shorten.length) {
      shorten = shorten.substring(0, shorten.length - 1);
    }
    return shorten;
  };

  Boolean.prototype.toStatus = function() {
    if (this === true) {
      console.log("Public");
      return "Public";
    } else {
      console.log("Private");
      return "Private";
    }
  };

}).call(this);
