// Generated by CoffeeScript 1.10.0
(function() {
  var ajax, event;

  ajax = {
    add: function(input) {
      return $.ajax('/Home/Add', {
        type: "POST",
        data: $('form').serialize(),
        beforeSend: function() {},
        success: function(response) {
          response = parseInt(response);
          console.log(response);
          if (response !== -1 && response !== 1) {
            return $('ul').append("<li data-id='" + response + "'><input type='checkbox' /><span>" + input + "</span>  <button>Remove</button></li>");
          } else {
            return alert("Error!");
          }
        },
        timeout: 3000,
        error: function(request, errorType, errorMessage) {
          return console.log("Error " + errorType + " with message: " + errorMessage + " [clientside]");
        },
        complete: function() {
          return console.log("Loading finished! [clientside]");
        }
      });
    },
    change: function(id) {
      return $.ajax('/Home/Change', {
        type: "POST",
        accept: 'application/json',
        data: {
          id: id,
          task: $(this).serializeArray()[0]
        },
        beforeSend: function() {},
        success: function(response) {
          response = parseInt(response);
          console.log(response);
          if (response !== -1) {
            console.log(this);
            return $(this).parent().html("" + ($(this).serializeArray()[0]));
          } else {
            return alert("Error!");
          }
        },
        timeout: 3000,
        error: function(request, errorType, errorMessage) {
          return console.log("Error " + errorType + " with message: " + errorMessage + " [clientside]");
        },
        complete: function() {
          return console.log("Loading finished! [clientside]");
        }
      });
    },
    remove: function(id) {
      return console.log('');
    }
  };

  event = {
    add: {
      submit: function(event) {
        event.preventDefault();
        return ajax.add($('.editor-field input').val());
      }
    },
    change: {
      submit: function(event) {
        event.preventDefault();
        console.log($(this).serializeArray()[0]);
        return ajax.change($(this).data("data-id"));
      },
      dblclick: function(event) {
        var html, value;
        event.preventDefault();
        value = $(this).html();
        console.log($(this));
        html = "<form id='changing'><input name='task' type='text' value='" + value + "' autofocus/></form>";
        console.log(html);
        $(this).html(html);
        $(this).children('input').first().focus();
        return console.log('ID: ' + $(this).data("id"));
      }
    }
  };

  $(document).on('ready', function() {
    $('#Task').focus();
    $('form').attr('autocomplete', 'off');
    $('form').first().on('submit', event.add.submit);
    $('li span').on('dblclick', event.change.dblclick);
    return $('#changing').on('submit', event.change.submit);
  });

}).call(this);
