// Generated by CoffeeScript 1.10.0
(function() {
  $(document).on('ready', function() {
    $('#Task').focus();
    $('form').attr('autocomplete', 'off');
    $('form').first().on('submit', modules.action.add.submit);
    $('.task').on('dblclick', modules.action.change.dblclick);
    $('tr').on('click', 'button', modules.action.remove.click);
    $('tr').on('change', '.checkbox', modules.action.check);
    return $('select').on('change', modules.action.select);
  });

}).call(this);
