// Generated by CoffeeScript 1.10.0
(function() {
  $(document).on('ready', function() {
    $('form').on('submit', function(event) {
      var errors, input;
      event.preventDefault();
      input = $('.editor-field input').val();
      console.log(input + " (input) [clientside]");
      errors = false;
      return $.ajax('/Home/Index', {
        type: "POST",
        data: $('form').serialize(),
        beforeSend: function() {},
        success: function(response) {
          console.log(response);
          if (response === "Error! [serverside]") {
            return errors = true;
          }
        },
        timeout: 3000,
        error: function(request, errorType, errorMessage) {
          errors = true;
          return console.log("Error " + errorType + " with message: " + errorMessage + " [clientside]");
        },
        complete: function() {
          console.log("Loading finished! [clientside]");
          if (!errors) {
            return $('ul').append("<li>" + input + "</li>");
          } else {
            return alert("Error!");
          }
        }
      });
    });
    return $('li').on('dblclick', function() {
      var value;
      console.log(this);
      console.log(typeof this);
      value = $(this).children('span').first();
      console.log(value.html());
      console.log(value);
      return value.html("<input type=text value=" + (value.html()));
    });
  });

}).call(this);
