// Generated by CoffeeScript 1.10.0
(function() {
  var ajax, event;

  ajax = {
    add: function(input) {
      return $.ajax('/Home/Add', {
        type: "POST",
        data: $(this).serialize(),
        beforeSend: function() {},
        success: function(response) {
          console.log(parseInt(response));
          if (parseInt(response !== -1)) {
            return $('ul').append("<li data-id='" + response + "'><input type='checkbox' /><span>" + input + "</span>  <button>Remove</button></li>");
          } else {
            return alert("Error!");
          }
        },
        timeout: 3000,
        error: function(request, errorType, errorMessage) {
          return console.log("Error " + errorType + " with message: " + errorMessage + " [clientside]");
        },
        complete: function() {
          return console.log("Loading finished! [clientside]");
        }
      });
    },
    change: function(id) {
      return $.ajax('/Home/Change', {
        type: "POST",
        data: {
          id: id,
          form: $(this).serialize()
        },
        beforeSend: function() {},
        success: function(response) {
          console.log(response);
          if (parseInt(response !== -1)) {
            return console.log(this);
          } else {
            return alert("Error!");
          }
        },
        timeout: 3000,
        error: function(request, errorType, errorMessage) {
          return console.log("Error " + errorType + " with message: " + errorMessage + " [clientside]");
        },
        complete: function() {
          return console.log("Loading finished! [clientside]");
        }
      });
    },
    remove: function(id) {
      return console.log('test');
    }
  };

  event = {
    add: {
      submit: function(event) {
        var errors, input;
        event.preventDefault();
        input = $('.editor-field input').val();
        console.log(input + " (input) [clientside]");
        errors = false;
        return ajax.add(input);
      }
    },
    change: {
      submit: function(event) {
        var errors;
        console.log($(this).serialize());
        console.log($(this).serialize().task);
        event.preventDefault();
        errors = false;
        return ajax.change($(this).data("data-id"));
      },
      dblclick: function() {
        var html, value;
        value = $(this).html();
        console.log($(this));
        html = "<form id='changing'><input name='task' type='text' value='" + value + "' autofocus/></form>";
        console.log(html);
        $(this).html(html);
        $(this).children('input').first().focus();
        return console.log('ID: ' + $(this).data("id"));
      }
    }
  };

  $(document).on('ready', function() {
    $('#Task').focus();
    $('form').attr('autocomplete', 'off');
    $('form').first().on('submit', event.add.submit);
    $('li span').on('dblclick', event.change.dblclick);
    return $('#changing').on('submit', event.change.submit);
  });

}).call(this);
